[server]
headless = true
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[theme]
# Anthropic Light theme (from official example)
primaryColor = "#cb785c"
backgroundColor = "#fdfdf8"
secondaryBackgroundColor = "#ecebe3"
textColor = "#3d3a2a"
linkColor = "#3d3a2a"
borderColor = "#d3d2ca"
showWidgetBorder = true
baseRadius = "0.75rem"
buttonRadius = "full"
font = "sans serif"
headingFontWeights = [600, 500, 500, 500, 500, 500]
headingFontSizes = ["3rem", "2rem"]
codeFont = "monospace"
codeFontSize = ".75rem"
codeBackgroundColor = "#ecebe4"
showSidebarBorder = true
chartCategoricalColors = ["#0ea5e9", "#059669", "#fbbf24"]

[theme.sidebar]
backgroundColor = "#f0f0ec"
secondaryBackgroundColor = "#ecebe3"
headingFontSizes = ["1.6rem", "1.4rem", "1.2rem"]
